import type { Metadata } from "next";

import "./globals.css";
import { hindSiliguri } from "./font";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("antialiased", hindSiliguri.className, "font-sans", geist.variable)}
    >
      <body className="">{children}</body>
    </html>
  );
}
