import type { Metadata } from "next";

import "./globals.css";
import { hindSiliguri } from "./font";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "travelBox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("antialiased", hindSiliguri.className, "font-sans", geist.variable)}
    >
      <body className="">
        {children}
        <Toaster position="top-right" richColors />
        </body>
    </html>
  );
}
